DLU release
lusprojects/lusprojects.github.io pull request #38
Opened 2021-12-26 16:00 UTC by ArkShocer

- Changed Status
- Added Github link
- Updated "How do I get a server emulator?" paragraph

2021-12-26 16:11 UTC, Jettford commented
@luxaritas

2021-12-26 18:31 UTC, Xiphoseer approved these changes
LGTM

2021-12-26 19:17 UTC, luxaritas requested changes
Minor wording tweak I think would work better - otherwise thanks for getting this updated!

2021-12-26 19:17 UTC, luxaritas commented on index.html
> +                For DLU setup questions please use the  <a href="https://discord.gg/jhTwGqYSKk" target="_blank"><i class="fab fa-discord"></i> LU Community Hub</a>.
```suggestion
                DLU has released <a href="https://github.com/DarkflameUniverse/DarkflameServer">their server emulator</a> which allows you to have a nearly feature-complete experience of LEGO Universe.
                For DLU setup questions, the best place to ask is the <a href="https://discord.gg/jhTwGqYSKk" target="_blank"><i class="fab fa-discord"></i>LU Community Hub</a>.
```

2022-01-01 01:47 UTC, luxaritas approved these changes
LGTM, thanks!

2022-01-01 01:47 UTC, merged